### ISSUE TITLE
Bump workers.rs To 0.3

### ISSUE THREAD

**Issue by DrewRidley** [logankeenan/axum-cloudflare-adapter#54]
There is currently a bug within ``workers-rs`` which prevents deployment through certain environments. This bug was resolved with this commit: https://github.com/cloudflare/workers-rs/commit/c7e966cf2b94afdf825e0aec7893c1a6cc6a8102.

The changes have been upstreamed to v 0.3.4. ``axum-cloudflare-adapter`` should update ``workers-rs`` accordingly.

**Comment by logankeenan** [comment]
version [0.13.0](https://crates.io/crates/axum-cloudflare-adapter/0.13.0) has been related
