### ISSUE TITLE
LICENSE on GitHub is missing

### ISSUE THREAD

**Issue by ghuntley** [logankeenan/axum-cloudflare-adapter#67]
Over at https://crates.io/crates/axum-cloudflare-adapter can see that project is marked as MIT but there's no MIT license in the GitHub repository :)

**Comment by logankeenan** [comment]
@ghuntley  - Thanks for the feedback. This has been fixed. It'll get updated on cargo in the latest release

https://github.com/logankeenan/axum-cloudflare-adapter/commit/03fd02d4b1fdc1e5212c80919a673db61b477187
